# Generated by Django 2.2.1 on 2019-05-26 01:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_teacherprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherProfile',
            new_name='Profile',
        ),
    ]
