# Generated by Django 2.2.1 on 2019-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190526_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_batch',
            field=models.CharField(default='2019', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='student_dept',
            field=models.CharField(default='EE', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='student_section',
            field=models.CharField(default='A', max_length=100),
        ),
    ]
